name: json5
description: JSON in dart (a port from json5 for nodejs)
version: 0.5.0
homepage: https://github.com/damphat/json5-dart

environment:
  sdk: '>=2.1.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
