name: json5
description: JSON5 for dart and flutter
version: 0.8.0
homepage: https://github.com/damphat/json5-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
